agents:
  queue: "t0-merge-queue"

steps:
  - label: "Clickhouse Cloud tests"
    commands:
      - "TENSORZERO_CLICKHOUSE_URL=$(buildkite-agent secret get secret_name)"
      - curl $TENSORZERO_CLICKHOUSE_URL --data-binary 'SHOW DATABASES'
      - curl -LsSf https://astral.sh/uv/0.6.17/install.sh | sh
      - uv run ./ui/fixtures/download-fixtures.py
      - ./ci/delete-clickhouse-dbs.sh
      - cargo build-e2e
      - |
        cargo run-e2e > e2e_logs.txt 2>&1 &
            count=0
            max_attempts=30
            while ! curl -s -f http://localhost:3000/health >/dev/null 2>&1; do
              echo "Waiting for gateway to be healthy..."
              sleep 1
              count=$((count + 1))
              if [ $count -ge $max_attempts ]; then
                echo "Gateway failed to become healthy after $max_attempts attempts"
                exit 1
              fi
            done
          export GATEWAY_PID=$!
      - cargo test-e2e-no-creds -- --skip test_concurrent_clickhouse_migrations
      - cat e2e_logs.txt
